spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'false'
    hibernate:
      ddl-auto: update
    show-sql: false
  datasource:
    password: admin
    username: postgres
    url: jdbc:postgresql://localhost:5432/vkrestapi
  cache:
    caffeine:
      spec: maximumSize=48,expireAfterWrite=1m

server:
  port: ${port:7070}
  error:
    include-message: always